name: mmac
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  flutter_riverpod: ^2.5.1
  universal_html: ^2.3.0
  shared_preferences: ^2.5.5
  open_filex: 
  share_plus: 
  pdf: 
  qr_flutter: 
  path_provider: ^2.1.6
  mobile_scanner: ^7.2.0
  permission_handler: ^12.0.3
  image_picker: ^1.2.2
  pdfrx: ^2.4.4
  flutter_secure_storage: ^10.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

  flutter_lints: ^6.0.0
  
flutter:
  assets:
    - assets/data/purposes.json
    - assets/data/accommodations.json
    - assets/images/
    - assets/images/department_logo.jpg
    - assets/images/national_flag.jpg
    - assets/images/national_logo.jpg
    - assets/images/nrc.jpg
    - assets/images/passport.jpg

  uses-material-design: true