name: mmac
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  flutter_riverpod: ^2.5.1
  shared_preferences: 
  pdf:
  #path_provider: 
  open_filex: 
  qr_flutter: 
  share_plus: 
   #flutter_pdfview: 
  #flutter_pdfview: 
  printing:
  path_provider: ^2.1.5
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  
flutter:
  assets:
    - assets/data/purposes.json
    - assets/data/accommodations.json
    - assets/images/
    - assets/images/department_logo.jpg
    - assets/images/national_flag.jpg
    - assets/images/national_logo.jpg
    - assets/images/nrc.jpg
    - assets/images/passport.jpg
  uses-material-design: true